#!/bin/env bash

ensure_directory_empty() {
  local c && c="$(find . \
    -mindepth 1 -maxdepth 1 |
    wc -c)"

  if [ "$c" -ne 0 ]; then
    echo rakeup: call rakeup within an empty directory >&2
    return 1
  fi
}

ensure_not_git_repository() {
  if git status >/dev/null 2>&1; then
    echo 'rakeup: do not rakeup within an existing git repository' >&2
    return 1
  fi
}

remove_dev_files() {
  rm -rf \
    .git .gitignore .gitmodules \
    .rake/scripts/install .rake/scripts/rakeup \
    .rake/test &&
    find .rake/scripts/lib/funcshional \
      -maxdepth 1 -type f,d \
      -not -name src -not -name funcshional \
      -exec rm -rf {} \;
}

remove_dev_git_modules() {
  git rm .rake/test/bats .rake/test/test_helper/bats-*
}

# TODO: find out a more programmatic way
modify_makefile() {
  cat <<EOF >Makefile
# TODO: specific option settings
MAKEFLAGS += --no-print-directory

# TODO: specific rake variable settings
SHELL := /bin/bash
RAKE_ROOT_DIR := \$(dir \$(realpath \$(lastword \$(MAKEFILE_LIST))))

# TODO: specific dependency setup
FUNCSHIONAL_ROOT_DIR := \${RAKE_ROOT_DIR}.rake/scripts/lib/funcshional/

export

# simple targets
# TODO: first, present compound targets then simple targets that are more for
# internal purposes
.PHONY: help
help:
	@. \${RAKE_ROOT_DIR}.rake/scripts/help.sh

# compound targets are forwarded to a potential sub
# NOTE: This FORCE target is to correctly handle subs that are directory and as
# such, considered up to date for make
.PHONY: FORCE
FORCE:;

%: FORCE
	@. \${RAKE_ROOT_DIR}.rake/scripts/forward_to_sub.sh \$@
EOF
}

modify_help_script() {
  sed -i -E '/contribution:/,/EOF/{/EOF/!d;}' .rake/scripts/help.sh
}

init_rake_project() {
  git clone https://github.com/MetaBarj0/rake.git &&
    cd rake &&
    remove_dev_git_modules &&
    git submodule update --init &&
    cd .. &&
    mv rake/* rake/.* . &&
    rm -r rake &&
    remove_dev_files &&
    modify_makefile &&
    modify_help_script &&
    git init &&
    echo .rake/.registered_sub >.gitignore
}

main() {
  ensure_directory_empty &&
    ensure_not_git_repository &&
    init_rake_project
}

main
