#!/bin/env bash

export RAKE_NO_SUB=1
export RAKE_SUB_DOES_NOT_EXIST=$((RAKE_NO_SUB + 1))
export RAKE_INVALID_SUB_DIRECTORY=$((RAKE_SUB_DOES_NOT_EXIST + 1))
export RAKE_NO_VALID_SUB=$((RAKE_INVALID_SUB_DIRECTORY + 1))
